### ISSUE TITLE
账号被封控，自动长时间运行，被风控概率很大

### ISSUE THREAD

**Issue by j5land** [JannsenYang/dingdong-helper#105]
1.现在(04-15)站点才比之前难抢了，站点运力开始逐步放力，所以需要拉长时间。
2.今天尝试了哨兵模式；
3.确认仅仅是小程序端账号被封；
4.今天(04-15)下午账号基本确认被风控了，进入订单页面无法选择送达时间。
4.1 进行了小程序账号退出测试；
4.2 进行了其他城市下单是否可行测试；
小程序端
![IMG_3040](https://user-images.githubusercontent.com/1421509/163524258-9b527c1c-6094-4d98-b778-96312b519bbb.JPG)

App端
![IMG_3041](https://user-images.githubusercontent.com/1421509/163524354-9c7c8111-8edc-4efc-8c8c-458bb3fd66e8.JPG)
![IMG_3042](https://user-images.githubusercontent.com/1421509/163525943-f55b142d-50bf-46b1-8491-a572372daa17.jpg)

**Comment by happytogether** [comment]
我也被封了，应该是由手机号判定被封控的，怎么app端跟小程序端还能一个被封，一个没有。

**Comment by cuipengcx** [comment]
我也是被风控了，获取配送时间一直提示"当前人多拥挤，请稍后尝试刷新页面"，手机app操作也是一样的，

**Comment by j5land** [comment]
> 

现在要想想看怎么破解这个风控了

**Comment by HenXian** [comment]
同样，今天早上6点  8点30  两次都下单失败。
且发现叮咚小程序和app 都进行了版本升级。

**Comment by JannsenYang** [comment]
我昨天也出现了 退出登录重进就好了

**Comment by JannsenYang** [comment]
> 同样，今天早上6点 8点30 两次都下单失败。 且发现叮咚小程序和app 都进行了版本升级。

应该没关系  今天6点和8点30我都下单了 正常

**Comment by happytogether** [comment]
作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : )
但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : (
换到别的城市的地址手动下单试试看，一样是人多拥挤。
你说昨天你也出现，退出登入重进就好了？
这边试过了还是不行。

**Comment by j5land** [comment]
已经尝试了微信叮咚小程序退出再登录还是被风控，目前我的案例，可以确认的是封的是微信小程序端账号。

目前的解法是：我手机苹果双卡双待，使用另外的的手机号进行注册，可以正常显示配送时间。

**Comment by j5land** [comment]
> 作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : ) 但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : ( 换到别的城市的地址手动下单试试看，一样是人多拥挤。 你说昨天你也出现，退出登入重进就好了？ 这边试过了还是不行。

作者不是万能的，试试换个亲朋好友的手机号重新登录即可。

**Comment by HenXian** [comment]
> > 作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : ) 但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : ( 换到别的城市的地址手动下单试试看，一样是人多拥挤。 你说昨天你也出现，退出登入重进就好了？ 这边试过了还是不行。
> 
> 作者不是万能的，试试换个亲朋好友的手机号重新登录即可。

请问，重新换个手机号注册后，还能用这个软件抢单且成功吗？

**Comment by cuipengcx** [comment]
> > > 作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : ) 但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : ( 换到别的城市的地址手动下单试试看，一样是人多拥挤。 你说昨天你也出现，退出登入重进就好了？ 这边试过了还是不行。
> > 
> > 
> > 作者不是万能的，试试换个亲朋好友的手机号重新登录即可。
> 
> 请问，重新换个手机号注册后，还能用这个软件抢单且成功吗？

可以的  换个账号 就是重新走一边抓包流程就好了

**Comment by j5land** [comment]
> > > 作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : ) 但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : ( 换到别的城市的地址手动下单试试看，一样是人多拥挤。 你说昨天你也出现，退出登入重进就好了？ 这边试过了还是不行。
> > 
> > 
> > 作者不是万能的，试试换个亲朋好友的手机号重新登录即可。
> 
> 请问，重新换个手机号注册后，还能用这个软件抢单且成功吗？

是的，可以的，重新抓包。
作者提供的脚步建议是高峰使用，2分钟没抢到就关了吧。
捡漏经验上建议人肉手动抢。

**Comment by coldtea07** [comment]
确实现在容易被封控，今天我的账号在6点只使用了两分钟，成功下单后，到8点半就发现被风控了，解决方法就是换个号码，反正有的吃就行，找亲戚朋友借号吧，。。

**Comment by tico-ji** [comment]
![image](https://user-images.githubusercontent.com/49098817/163534325-8ee2492e-f79b-42fe-9ec4-585c9d3d1360.png)
抓包显示,小程序提交订单时增加了运力check的接口,目前手动增加这一步检查,由于运力一直未开放,无法得知后续流程是否有变化,目前哨兵模式运行中.
另外,作者有交流群吗,我开发了白名单类目库存监控以及白名单商品自动添加购物车的功能,大伙可以交流交流哈

**Comment by wJDKnight** [comment]
> ![image](https://user-images.githubusercontent.com/49098817/163534325-8ee2492e-f79b-42fe-9ec4-585c9d3d1360.png) 抓包显示,小程序提交订单时增加了运力check的接口,目前手动增加这一步检查,由于运力一直未开放,无法得知后续流程是否有变化,目前哨兵模式运行中. 另外,作者有交流群吗,我开发了白名单类目库存监控以及白名单商品自动添加购物车的功能,大伙可以交流交流哈

哇，白名单这个功能厉害了。交流群的话被官方抓到要惹麻烦的。你可以单独开一个repo介绍一下吗？

**Comment by coldtea07** [comment]
> ![image](https://user-images.githubusercontent.com/49098817/163534325-8ee2492e-f79b-42fe-9ec4-585c9d3d1360.png) 抓包显示,小程序提交订单时增加了运力check的接口,目前手动增加这一步检查,由于运力一直未开放,无法得知后续流程是否有变化,目前哨兵模式运行中. 另外,作者有交流群吗,我开发了白名单类目库存监控以及白名单商品自动添加购物车的功能,大伙可以交流交流哈

大佬直接开个PR啊

**Comment by liaomengge** [comment]
>  大佬，可以在自己的仓库提一下，我参考一下呗 。

**Comment by tico-ji** [comment]
> > ![image](https://user-images.githubusercontent.com/49098817/163534325-8ee2492e-f79b-42fe-9ec4-585c9d3d1360.png) 抓包显示,小程序提交订单时增加了运力check的接口,目前手动增加这一步检查,由于运力一直未开放,无法得知后续流程是否有变化,目前哨兵模式运行中. 另外,作者有交流群吗,我开发了白名单类目库存监控以及白名单商品自动添加购物车的功能,大伙可以交流交流哈
> 
> 大佬直接开个PR啊

貌似没法开PR,而且最初我git账号忘记了,所以本地版本没关联到我的仓库,一会搞一下,可以简单说一下思路
首先通过抓包,找到你想买的类目ID(categoryId),找个地方缓存起来
增加checkStock方法,根据类目id进行查询,得到商品列表(测试时打印出来,记下你想要的商品id,后面添加购物车要用)
增加addCart方法,通过productId进行添加,(此处可根据预设的商品白名单进行过滤).步骤是:
1.先访问详情页得到productDetail,有的商品需要选择规格,这里默认选第一个.
2.得到sizeId后(有可能没有sizeId,可直接购买),拼装请求完成购物车添加.
貌似没法贴代码文件...本来想把扩展类扔上来的

**Comment by liaomengge** [comment]
> 思路没问题，不过意义不是特别大，你本身就可以再app上把需要的商品加到购物车去，没必要手动抓包，看到那些produceId加进到购物车中，其实你再抢购的时候，很多商品都是没货的， 所以能下单成功就不错了。 提前在购物车加你想要的商品就可以了，自动抓包，然后把这些商品id加到购物车本身没有太大的必要，而且增加了程序的复杂度，开箱即用即可。

**Comment by tico-ji** [comment]
> > 思路没问题，不过意义不是特别大，你本身就可以再app上把需要的商品加到购物车去，没必要手动抓包，看到那些produceId加进到购物车中，其实你再抢购的时候，很多商品都是没货的， 所以能下单成功就不错了。 提前在购物车加你想要的商品就可以了，自动抓包，然后把这些商品id加到购物车本身没有太大的必要，而且增加了程序的复杂度，开箱即用即可。

的确是这样,只是我一开始没参与抢菜,都是我老婆在弄,然后有天她让我一起帮忙,我打开进去发现没法添加到购物车(她之前有添加但是失效了),想参与抢菜的话就要先等服务端开放库存,这个就很难受了,所以才在作者原基础上进行了扩展,而且扩展api使用了代理模式,作者的原逻辑没有改变,只是对部分功能进行增强,以及流程编排上的改动.
复杂度的话,由于添加购物车和下单是两个独立线程,应该没什么影响.

**Comment by chenqiny** [comment]
> > > > 作者你好，首先代替朋友在普陀没东西吃的老父亲感谢你，他们不会订菜，靠著一个在医院工作的女儿早上六点上岗前抢菜，没有一次抢到的。抢到了以后他们真的非常开心 : ) 但可惜的是，可能不能再帮他们订了，今天订完好像被封控了 : ( 换到别的城市的地址手动下单试试看，一样是人多拥挤。 你说昨天你也出现，退出登入重进就好了？ 这边试过了还是不行。
> > > 
> > > 
> > > 作者不是万能的，试试换个亲朋好友的手机号重新登录即可。
> > 
> > 
> > 请问，重新换个手机号注册后，还能用这个软件抢单且成功吗？
> 
> 可以的 换个账号 就是重新走一边抓包流程就好了

可以直接打电话投诉吧，我都充VIP了，不就抢点菜吗。

**Comment by liaomengge** [comment]
> 购物车商品失效，其实没有事的，只要放货了还是可以抢到的，不需要再次添加到购物车，我今天直接在服务器上挂了一个捡漏，一个高峰2个进程刷（我的购物车都是失效的），还是抢到了2单，这个是不影响的。 因为作者有勾选全选购物车的。所以你这个需要额外的手动的添加商品id白名单（这一块个人觉得其实没有必要）。

**Comment by tico-ji** [comment]
> > 购物车商品失效，其实没有事的，只要放货了还是可以抢到的，不需要再次添加到购物车，我今天直接在服务器上挂了一个捡漏，一个高峰2个进程刷（我的购物车都是失效的），还是抢到了2单，这个是不影响的。 因为作者有勾选全选购物车的。所以你这个需要额外的手动的添加商品id白名单（这一块个人觉得其实没有必要）。

给新加入的人用的,我现在也用不到啦
而且假如已经下单成功了,那购物车里就没了,这时候又要等放货重新添加了

**Comment by tico-ji** [comment]
![image](https://user-images.githubusercontent.com/49098817/163553988-96fbca60-c862-41e5-9c46-3a7cae5c5f64.png)
刚验证过,流程改过捡漏成功~

**Comment by liaomengge** [comment]
> 不可能每次抢那几样东西，而且这个需要抓包，手动添加商品id白名单，我直接run在服务器上，没必要每次改代码？ 即使有需要复购的，直接再次添加在购物车就可以了。

**Comment by wJDKnight** [comment]
> > > 购物车商品失效，其实没有事的，只要放货了还是可以抢到的，不需要再次添加到购物车，我今天直接在服务器上挂了一个捡漏，一个高峰2个进程刷（我的购物车都是失效的），还是抢到了2单，这个是不影响的。 因为作者有勾选全选购物车的。所以你这个需要额外的手动的添加商品id白名单（这一块个人觉得其实没有必要）。
> 
> 给新加入的人用的,我现在也用不到啦 而且假如已经下单成功了,那购物车里就没了,这时候又要等放货重新添加了

这个功能对于美团买菜很有用。美团是不支持没货的商品添加购物车的。和叮咚不一样。话说大佬有兴趣做个美团的抢菜吗？

**Comment by liaomengge** [comment]
> ![image](https://user-images.githubusercontent.com/49098817/163553988-96fbca60-c862-41e5-9c46-3a7cae5c5f64.png) 刚验证过,流程改过捡漏成功~

加运力check这一块没毛病；手动抓包，缓存白名单，这一块可选，不是必要流程。

**Comment by liaomengge** [comment]
>  是的，美团买菜 加购物车还是必要的，这个不能手动加。



> > > > 购物车商品失效，其实没有事的，只要放货了还是可以抢到的，不需要再次添加到购物车，我今天直接在服务器上挂了一个捡漏，一个高峰2个进程刷（我的购物车都是失效的），还是抢到了2单，这个是不影响的。 因为作者有勾选全选购物车的。所以你这个需要额外的手动的添加商品id白名单（这一块个人觉得其实没有必要）。
> > 
> > 
> > 给新加入的人用的,我现在也用不到啦 而且假如已经下单成功了,那购物车里就没了,这时候又要等放货重新添加了
> 
> 这个功能对于美团买菜很有用。美团是不支持没货的商品添加购物车的。和叮咚不一样。话说大佬有兴趣做个美团的抢菜吗？

**Comment by tico-ji** [comment]
> > 不可能每次抢那几样东西，而且这个需要抓包，手动添加商品id白名单，我直接run在服务器上，没必要每次改代码？ 即使有需要复购的，直接再次添加在购物车就可以了。

是的呀,我也说了无所谓的,我只是懒得去手动刷库存添加进去,而且这个刷库存跟抢单是两个独立的功能,我是两个一起开的,互不影响

**Comment by tico-ji** [comment]
之所以搞这个功能,一部分原因是一些青菜之类的,复购会比较多,每次抢单成功还要去等库存重新添加略显麻烦.
还有一部分原因是老婆会经常点一些不一样的东西,而且基本跟我说的时候都是没库存的.现在叮咚放货的时间好像也不是特别规律了,因为我在测试库存监控的时候,发现时不时的就有上新,持续3分钟左右就无了,如果你想要什么东西,我觉得还是有使用场景的

**Comment by tico-ji** [comment]
对了,说了这么久,感谢作者大大!辛苦了 @JannsenYang

**Comment by tico-ji** [comment]
> > ![image](https://user-images.githubusercontent.com/49098817/163553988-96fbca60-c862-41e5-9c46-3a7cae5c5f64.png) 刚验证过,流程改过捡漏成功~
> 
> 加运力check这一块没毛病；手动抓包，缓存白名单，这一块可选，不是必要流程。

刚才验证了一下,原来不是一定要有库存才能加到购物车的,看来还是我玩的不6啊,这么说的话的确不是必要流程...
不过这个接口可以添加页面上不给加到购物车的商品

**Comment by liaomengge** [comment]
>  美团的必须有库存才能加入，你这个思路其实是正确的，没毛病。。

**Comment by Louzhichen** [comment]
> > > ![image](https://user-images.githubusercontent.com/49098817/163553988-96fbca60-c862-41e5-9c46-3a7cae5c5f64.png) 刚验证过,流程改过捡漏成功~
> > 
> > 
> > 加运力check这一块没毛病；手动抓包，缓存白名单，这一块可选，不是必要流程。
> 
> 刚才验证了一下,原来不是一定要有库存才能加到购物车的,看来还是我玩的不6啊,这么说的话的确不是必要流程... 不过这个接口可以添加页面上不给加到购物车的商品

能否分享一下运力检查的代码？
