### ISSUE TITLE
新版不能获取地址

### ISSUE THREAD

**Issue by zric** [JannsenYang/dingdong-helper#109]
开始获取收货人信息
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null
        at Api.sign(Api.java:41)
        at Api.checkUserConfig(Api.java:139)
        at UserConfig.main(UserConfig.java:25)
没有可用的默认收货地址，请自行登录叮咚设置该站点可用的默认收货地址

**Comment by RecoverySky** [comment]
同问题

**Comment by controversialTopic** [comment]
加一，同样的问题

**Comment by JannsenYang** [comment]
jdk版本发一下  根目录新增了一个sign.js文件 确认一下是不是存在

**Comment by controversialTopic** [comment]
jdk1.8.0_311，存在这个sign.js

**Comment by JannsenYang** [comment]
更新一下代码试试 我在stackoverflow上找的解决方案

**Comment by controversialTopic** [comment]
好的，感谢

**Comment by zric** [comment]
更新了api试过 问题依旧

**Comment by zric** [comment]
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**Comment by RecoverySky** [comment]
> 

还是同样的问题

**Comment by controversialTopic** [comment]
> 

试一下jdk1.8,我刚才看错了版本号了，默认是17.0.1我切换到了1.8.0_311后现在运行成功了

**Comment by RecoverySky** [comment]
> 更新一下代码试试 我在stackoverflow上找的解决方案

问题依旧在

**Comment by JannsenYang** [comment]
查了一下资料 高版本的java把这个功能去掉了  我兼容一下吧 高版本也能跑 但是不签名 尽量还是用1.8吧

**Comment by controversialTopic** [comment]
切换了一些jdk版本x现在可以了
![Uploading WHJ_R(FO%$JX0}(K@8C88GP.png…]()

**Comment by mwdxr2002** [comment]
openjdk version "17.0.2" 2022-01-18 同样的报错，麻烦给个不签名的版本

**Comment by JannsenYang** [comment]
加了一版警告和兼容 不签名也能使用  还是尽量使用1.8吧

**Comment by mwdxr2002** [comment]
多谢,可以使用了
