### ISSUE TITLE
city_number NullPointerException

### ISSUE THREAD

**Issue by Solawhite** [JannsenYang/dingdong-helper#113]
![Snipaste](https://user-images.githubusercontent.com/32129243/163583539-c3e393a7-094f-424d-8b91-4883b011194b.png)

 Api.checkUserConfig() 异常
有默认地址，站点收货人均正常，city_number = null

**Comment by JannsenYang** [comment]
按理来说这个数据应该不会空的  我兼容了一下 更新一下代码
