### ISSUE TITLE
UserConfig.java 无法运行求指导

### ISSUE THREAD

**Issue by RoyTse1024** [JannsenYang/dingdong-helper#117]
大佬，救救孩子吧，已经一周多没有抢到菜了。。。

JAVA小白，自己看教程用Charles抓包了用户信息。但到了最后一步，把用户信息配置到UserConfig.java后，点击“RUN”却始终如下图报错，无法运行。已经反复确认了抓包的用户信息无误，还希望请大佬指导！！谢谢🙇‍
![Snipaste_2022-04-16_04-12-29](https://user-images.githubusercontent.com/103232548/163628854-8c6b35de-9d41-4a99-a5db-e7975b85140c.png)

**Comment by windherd** [comment]
不要用jdk16，推荐用java8

**Comment by RoyTse1024** [comment]
> 不要用jdk16，推荐用java

感谢👍
