### ISSUE TITLE
想问一下maven报错怎么处理？

### ISSUE THREAD

**Issue by a1198375223** [JannsenYang/dingdong-helper#12]
![image](https://user-images.githubusercontent.com/24283635/162616751-b3c3ecac-8fe7-4896-98c9-bd44541dd38c.png)

如果可以的话可以添加一个wx交流一下吗？15520729130

**Comment by JannsenYang** [comment]
这个错应该是你装的maven版本太低了  1升级你的maven 2修改代码中maven的版本

根pom里 把这两个版本改成支持你maven的版本  你自己有没有maven项目 看一下版本多少 挪过来就可以了
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>

**Comment by a1198375223** [comment]
怎么查看这两个的对应版本呢？

**Comment by a1198375223** [comment]
我新建的maven项目没有这两个配置

**Comment by a1198375223** [comment]
![image](https://user-images.githubusercontent.com/24283635/162617704-39c477b4-193b-4b9e-b8af-d58116c31a1c.png)

**Comment by JannsenYang** [comment]
> ![image](https://user-images.githubusercontent.com/24283635/162617704-39c477b4-193b-4b9e-b8af-d58116c31a1c.png)

重新拉一下代码 我更新了pom配置 我之前用的是微服务的配置 直接用你截图里的就可以了  因为不用打包

**Comment by a1198375223** [comment]
![image](https://user-images.githubusercontent.com/24283635/162618722-89211418-9c8b-40a1-95bb-16a3b4c52dbf.png)
现在还是报红，是不是我环境有问题？

**Comment by a1198375223** [comment]
![image](https://user-images.githubusercontent.com/24283635/162619194-c846dd45-adca-4c5b-8b53-41530d300b05.png)

**Comment by JannsenYang** [comment]
感觉应该是和你maven的仓库设置有关 idea里设置maven 直接用idea内置的maven试试

**Comment by a1198375223** [comment]
我使用的就是默认的idea的maven，如果大佬方便的话，能否加一下上面的联系方式（第一条评论）。我向您请教一下

**Comment by a1198375223** [comment]
我解决了，默认的settings.xml文件是不存在的。需要手动下载一个maven引用里面的settings.xml，或者是自己copy一份。

**Comment by a1198375223** [comment]
现在还是拉不到maven包，是不是我环境有问题？
