### ISSUE TITLE
charles无法抓取桌面版微信小程序信息

### ISSUE THREAD

**Issue by iPoring** [JannsenYang/dingdong-helper#124]
其他网站抓取都正常，证书配置都OK，就是微信小程序没有显示出来，这是为什么呢...（Windows10）

**Comment by jimmyk1m** [comment]
看看这个，可用
https://www.jianshu.com/p/f87512ed7b21

**Comment by iPoring** [comment]
感谢

> 看看这个，可用
> https://www.jianshu.com/p/f87512ed7b21
