### ISSUE TITLE
提交订单失败,当前下单总金额：xxx 失败:抱歉，同一时间下单人数过多，建议您稍后再试

### ISSUE THREAD

**Issue by SnoopyGo** [JannsenYang/dingdong-helper#132]
早上6点钟抢到了一次，程序就只运行了不到1分钟的样子，后来去APP点击付款一直显示人数过多，无法付款，眼巴巴的看着订单被取消。

刚才打开程序，我所在站点还有运力，就随便跑了一下测试类，发现输出：当前下单总金额：xxx 失败:抱歉，同一时间下单人数过多，建议您稍后再试；
我手动在APP上试着提交订单，同样的结果；但是换到杭州的地址，就一切正常，可以提交订单，也可以付款，请问下有大佬知道原因吗？
![20~(8%92J88OMB~_JR@OR3S](https://user-images.githubusercontent.com/52532384/163669331-2891a99d-bcdd-4e21-bd3c-079384881bee.jpg)

另分享一个安卓11以上可以抓包APP的办法：
安装小黄鸟、vmospro这两个配合vmos里边的xposed框架以及root权限，可以实现在真机里边启动小黄鸟，在虚机里边进行抓包APP

**Comment by hugulas** [comment]
限流了

**Comment by SnoopyGo** [comment]
> 限流了

早上6点第一单抢到不能付款也是限流吗？请问这个有办法解决吗

**Comment by githubw2015** [comment]
你的账号已经风控了一般 早上 6.00， 8.30 才会报这种，其他时间段，你账号要被封

**Comment by SnoopyGo** [comment]
> 你的账号已经风控了一般 早上 6.00， 8.30 才会报这种，其他时间段，你账号要被封

这个无解吗？

**Comment by newwan** [comment]
换账号

**Comment by liuuteen** [comment]
我也是这样，而且我另外一个号没有用脚本，手动抢，点的频繁了。也被风控了

**Comment by liuuteen** [comment]
然后换了一个新号测试，一下就买到了。

**Comment by SnoopyGo** [comment]
> 

我是早上第一单抢到了不能付款，我在某红书上也看到不少人，自己手动人肉捡漏的订单也无法付款。吐了，........
