### ISSUE TITLE
抢购时提示“购物车无可买的商品”，但手机APP手动刷新后可到达选时间环节

### ISSUE THREAD

**Issue by asakali** [JannsenYang/dingdong-helper#14]
<img width="416" alt="Xnip2022-04-11_06-15-28" src="https://user-images.githubusercontent.com/17283599/162642233-df773b7e-ffb7-4219-8cf3-69dc348b818c.png">

5点59分运行，最终结果如上图。

但是在手机APP上手动尝试，多次是可以进到选时间环节的。

**Comment by JannsenYang** [comment]
第一确认购物车全选按钮是否勾上 如果不是的话就是站点假库存 你手机上的购物车是本地缓存数据 6点一到购物车的商品就全下架了  你要到真正下单的时候才会验证和提示失效  根据同事的反馈有少数人出现  我本人也是 几百块的购物车最后成交了50块 我第一时间用手机人工刷了购物车 确实都没货了

**Comment by JannsenYang** [comment]
更新一下代码 重新执行一下UserInfo 新增了一段检验站点id的代码 确认一下站点id是否和收货地址匹配

**Comment by asakali** [comment]
谢谢回复，在8点半的那次，虽然我没抢到，但我临时加了个有货的商品进购物车，然后抢购成功了。
看来就是我们站的东西特别少的原因。
