### ISSUE TITLE
一些接口的nars的值是不是不对

### ISSUE THREAD

**Issue by bestspiders** [JannsenYang/dingdong-helper#150]
比如cart这个接口
`var body='{"uid": "", "longitude": "", "latitude": "", "station_id": "5c1f049e716de13e768b4f17", "city_number": "0101", "api_version": "9.50.0", \
"app_version": "2.83.0", "applet_source":"", "channel": "applet", "app_client_id": "4", "sharer_uid": "", "s_id": "27ad75373439b2c37a27286209b2d496", "openid": "", \
"h5_source": "", "time": "1650173241", "device_token": "WHJMrwNw1k/FKPjcOOgRd+CMpKxy8Q9t0fP+7jmLlzRjJCPkHFuDzN2YOb0psou1TMRL+dakaTQBTio6MyC3nKx8W8RUkpivydCW1tldyDzmauSxIJm5Txg==1487582755342", \
"is_load": "1", "ab_config": {"key_onion": "D", "key_cart_discount_price": "C"}};'
console.log(sign(body));`
凡是里面再带一层数组的请求nars都不对，其它的请求nars值都对，有没有大佬解释下。（为了隐私，例子里删除了我的隐私数据）

**Comment by JannsenYang** [comment]
明天有空再看一下 没打开电脑

**Comment by bcpxqz** [comment]
sesi的计算也有问题，可以验证下  ,里面的两个调用不是md5 是 hex_md5

**Comment by JannsenYang** [comment]
> 

我看了这md5的npm库介绍  md5默认就是用hex算法

**Comment by JannsenYang** [comment]
sesi就不可能验证 中间带着随机数  只有nars才能保证数据一样签名一样

**Comment by JannsenYang** [comment]
刚刚试了一把你说的cart接口是对的 

 "ab_config": {"key_onion": "D", "key_cart_discount_price": "C"}  你这一行有问题，这里是字符串，不是对象

**Comment by JannsenYang** [comment]
看一下协议 这是get请求 queryparams  value只能为字符串 所以这里是json格式的字符串 而不是json对象   post请求中form表单中也是基本类型 不能是json对象

**Comment by bcpxqz** [comment]
> > 
> 
> 我看了这md5的npm库介绍 md5默认就是用hex算法

i.hex_md5和md5的代码不同

数据
{
    "city_number": "0101",
    "api_version": "9.50.0",
    "app_version": "2.83.0",
    "applet_source": "",
    "channel": "applet",
    "app_client_id": "4",
    "sharer_uid": ""
}
错误sesi
{
    nars: 'abb92f568ad4a88c15a49031b3fb086e',
    sesi: 'Dpo8HiMb708e538645d0c46661e0f1a89f3b98e'
}
正确sesi
{
    nars: 'abb92f568ad4a88c15a49031b3fb086e',
    sesi: 'Dpo8HiM159c16321c0d8a448e7613e0ff6072df'
}

**Comment by bcpxqz** [comment]
> sesi就不可能验证 中间带着随机数 只有nars才能保证数据一样签名一样

sesi前7位带了随机数

**Comment by JannsenYang** [comment]
> > > 
> > 
> > 
> > 我看了这md5的npm库介绍 md5默认就是用hex算法
> 
> i.hex_md5和md5的代码不同
> 
> 数据 { "city_number": "0101", "api_version": "9.50.0", "app_version": "2.83.0", "applet_source": "", "channel": "applet", "app_client_id": "4", "sharer_uid": "" } 错误sesi { nars: 'abb92f568ad4a88c15a49031b3fb086e', sesi: 'Dpo8HiMb708e538645d0c46661e0f1a89f3b98e' } 正确sesi { nars: 'abb92f568ad4a88c15a49031b3fb086e', sesi: 'Dpo8HiM159c16321c0d8a448e7613e0ff6072df' }

没看仔细 纠正了 随机数并没有参与后面那串字符串的摘要算法   我把你搞成1楼同一个人了  你二楼的那个也字让我误会了   nars应该是没问题的

**Comment by bestspiders** [comment]
`var body='{"uid": "6257dc3fadeb2f000195d586", "longitude": "121.246362", "latitude": "31.066583", "station_id": "5c1f049e716de13e768b4f17", "city_number": "0101", "api_version": "9.50.0", \
"app_version": "2.83.0", "applet_source":"", "channel": "applet", "app_client_id": "4", "sharer_uid": "", "s_id": "27ad75373439b2c37a27286209b2d496", "openid": "osP8I0QbvLCqc3CK6WA_7IhjkKgI", \
"h5_source": "", "time": "1650248622", "device_token": "WHJMrwNw1k/FKPjcOOgRd+CMpKxy8Q9t0fP+7jmLlzRjJCPkHFuDzN2YOb0psou1TMRL+dakaTQBTio6MyC3nKx8W8RUkpivydCW1tldyDzmauSxIJm5Txg==1487582755342", \
"is_load": "1", "ab_config": "{\\"key_onion\\":\\"D\\",\\"key_cart_discount_price\\":\\"C\\"}"}';

console.log(sign(body));
`
谢谢了，改为字符串正常

**Comment by zhanghugh** [comment]
看了下，在下单order的 post中“https://maicai.api.ddxq.mobi/order/addNewOrder”
好像package_order、showMsg、showData、ab_config没有参与md5运算，会导致nars不正确。
