### ISSUE TITLE
此程序的命令行版本

### ISSUE THREAD

**Issue by soundofautumn** [JannsenYang/dingdong-helper#156]
自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
[dingdong-helper](https://github.com/soundofautumn/dingdong-helper)

**Comment by cxjnevergiveup** [comment]
> 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> 
> [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)

请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个

**Comment by soundofautumn** [comment]
打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
不会编译的话直接下release的文件就好了

**Comment by cxjnevergiveup** [comment]
> > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> 
> > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> 
> > 
> 
> > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> 
> 
> 
> 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> 
> 不会编译的话直接下release的文件就好了
> 
> 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)

**Comment by soundofautumn** [comment]
> > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> > 
> > 
> > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> > 
> > 
> > > 
> > 
> > 
> > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> > 
> > 
> > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> > 不会编译的话直接下release的文件就好了
> > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)

已更新，你再重新下一个试试看

**Comment by cxjnevergiveup** [comment]
> > > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> 
> > > 
> 
> > > 
> 
> > > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> 
> > > 
> 
> > > 
> 
> > > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> 
> > > 不会编译的话直接下release的文件就好了
> 
> > > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)
> 
> 
> 
> 已更新，你再重新下一个试试看

请问run三个进程是不是 用这个多开cmd比多开idea效率高 运行快

**Comment by soundofautumn** [comment]
> > > > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> > 
> > 
> > > > 不会编译的话直接下release的文件就好了
> > 
> > 
> > > > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)
> > 
> > 
> > 已更新，你再重新下一个试试看
> 
> 请问run三个进程是不是 用这个多开cmd比多开idea效率高 运行快

那肯定，但其实线程数什么的可以自己通过加参数调的，可以通过加-h来看有哪些参数可以指定

**Comment by cxjnevergiveup** [comment]
> > > > > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> 
> > > 
> 
> > > 
> 
> > > > > 不会编译的话直接下release的文件就好了
> 
> > > 
> 
> > > 
> 
> > > > > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)
> 
> > > 
> 
> > > 
> 
> > > 已更新，你再重新下一个试试看
> 
> > 
> 
> > 请问run三个进程是不是 用这个多开cmd比多开idea效率高 运行快
> 
> 
> 
> 那肯定，但其实线程数什么的可以自己通过加参数调的，可以通过加-h来看有哪些参数可以指定

哥 能教一下具体怎么编译成jar文件的嘛

我看网上maven项目编译成jar的教程看不太懂 如果有时间能以这个项目做个例子 简单说说步骤嘛 多谢

**Comment by soundofautumn** [comment]
> > > > > > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 不会编译的话直接下release的文件就好了
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 已更新，你再重新下一个试试看
> > 
> > 
> > > 
> > 
> > 
> > > 请问run三个进程是不是 用这个多开cmd比多开idea效率高 运行快
> > 
> > 
> > 那肯定，但其实线程数什么的可以自己通过加参数调的，可以通过加-h来看有哪些参数可以指定
> 
> 哥 能教一下具体怎么编译成jar文件的嘛
> 
> 我看网上maven项目编译成jar的教程看不太懂 如果有时间能以这个项目做个例子 简单说说步骤嘛 多谢

就改改pom.xml就行了，你可以参考一下这个项目里的，加个plugin就行了，其他的可以网上找教程

**Comment by cxjnevergiveup** [comment]
> > > > > > > > > 自己改了改，可以通过加参数来更改模式，配置也单独独立出文件
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > [dingdong-helper](https://github.com/soundofautumn/dingdong-helper)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > 请问大佬如何运行这个jar包是 把main下面的每个.Java文件都运行一遍吗 如何指定运行某一个
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 打包成jar后直接在命令行下执行java -jar <jar包名> <参数>
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 不会编译的话直接下release的文件就好了
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 报错这个![image](https://user-images.githubusercontent.com/52702777/163952362-73a36177-ffa5-4452-bffb-39cec7219676.jpeg)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > 已更新，你再重新下一个试试看
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 请问run三个进程是不是 用这个多开cmd比多开idea效率高 运行快
> 
> > > 
> 
> > > 
> 
> > > 那肯定，但其实线程数什么的可以自己通过加参数调的，可以通过加-h来看有哪些参数可以指定
> 
> > 
> 
> > 哥 能教一下具体怎么编译成jar文件的嘛
> 
> > 
> 
> > 我看网上maven项目编译成jar的教程看不太懂 如果有时间能以这个项目做个例子 简单说说步骤嘛 多谢
> 
> 
> 
> 就改改pom.xml就行了，你可以参考一下这个项目里的，加个plugin就行了，其他的可以网上找教程

谢谢大佬回复 对了 还有那个-选参数的 需要自己写到代码里吗 就是-s是哨兵这个-s是自己写了才会在命令行有这个功能吗 

然后可以指定参数 比如说把线程改一下 这个是我编译好就直接可以的 还是说要自己写个代码才可以实现

**Comment by soundofautumn** [comment]
比如哨兵模式就是java -jar dingdong-helper-1.0.0.jar -s
提交订单执行线程数改为8 并发执行策略改为2就是java -jar dingdong-helper-1.0.0.jar -st 8 -p 2

**Comment by cxjnevergiveup** [comment]
> 比如哨兵模式就是java -jar dingdong-helper-1.0.0.jar -s
> 
> 提交订单执行线程数改为8 并发执行策略改为2就是java -jar dingdong-helper-1.0.0.jar -st 8 -p 2


![image](https://user-images.githubusercontent.com/52702777/164957064-8e1a7293-dbb3-4b56-96c4-1d588a007ba2.jpeg)
![image](https://user-images.githubusercontent.com/52702777/164957068-d88dcecc-fb88-4b73-81f5-6abfaf219c78.jpeg)
老哥这里报错了 参数错误

**Comment by soundofautumn** [comment]
兄弟你为什么不直接在我fork的那个项目下提issue啊 😂 在改了待会我更新一下

**Comment by cxjnevergiveup** [comment]
> 兄弟你为什么不直接在我fork的那个项目下提issue啊 😂 在改了待会我更新一下

那个提不了issue不知道为啥

**Comment by cxjnevergiveup** [comment]
> 兄弟你为什么不直接在我fork的那个项目下提issue啊 😂 在改了待会我更新一下

请问大哥更新出来 怎么没有.jar文件了 

是个源代码 我下载下来了 需要怎么操作才能变成.jar文件

**Comment by soundofautumn** [comment]
> > 兄弟你为什么不直接在我fork的那个项目下提issue啊 😂 在改了待会我更新一下
> 
> 请问大哥更新出来 怎么没有.jar文件了
> 
> 是个源代码 我下载下来了 需要怎么操作才能变成.jar文件

我单独又建了个仓库，现在应该可以提issue了，操作方法也更新到README里面了
[dingdong-helper](https://github.com/soundofautumn/dingdong-helper-console)
