### ISSUE TITLE
上午下了两单支付成功

### ISSUE THREAD

**Issue by BarryAlanPan** [JannsenYang/dingdong-helper#162]
如题，第一单是8:30，第二单是哨兵抢到的，电脑端小程序，支付会弹出二维码，手机扫码付款就行

**Comment by BarryAlanPan** [comment]
下午第三单又中了

**Comment by ZTR321** [comment]
是抢到单然后在电脑上小程序支付吗

**Comment by BarryAlanPan** [comment]
> 是抢到单然后在电脑上小程序支付吗

是的，会弹出来二维码

**Comment by chaoyu** [comment]
> > 是抢到单然后在电脑上小程序支付吗
> 
> 是的，会弹出来二维码

能不能描述一下你的运行环境和操作步骤？你的意思是自动程序在跑的同时，电脑端小程序也是开着的，然后下单成功之后，小程序那边直接会弹出二维码，然后手机直接扫码支付？

**Comment by BarryAlanPan** [comment]
> > > 是抢到单然后在电脑上小程序支付吗
> > 
> > 
> > 是的，会弹出来二维码
> 
> 能不能描述一下你的运行环境和操作步骤？你的意思是自动程序在跑的同时，电脑端小程序也是开着的，然后下单成功之后，小程序那边直接会弹出二维码，然后手机直接扫码支付？

exactly

**Comment by totpaula** [comment]
想请教下哨兵模式的参数怎么调整比较安全？

**Comment by SnoopyGo** [comment]
> > > > 是抢到单然后在电脑上小程序支付吗
> > > 
> > > 
> > > 是的，会弹出来二维码
> > 
> > 
> > 能不能描述一下你的运行环境和操作步骤？你的意思是自动程序在跑的同时，电脑端小程序也是开着的，然后下单成功之后，小程序那边直接会弹出二维码，然后手机直接扫码支付？
> 
> exactly

您好，请问是pc端微信小程序一直是停留在购物车页面吗？然后会自动到结算--提交订单--弹出付款二维码吗？

**Comment by BarryAlanPan** [comment]
> > > > > 是抢到单然后在电脑上小程序支付吗
> > > > 
> > > > 
> > > > 是的，会弹出来二维码
> > > 
> > > 
> > > 能不能描述一下你的运行环境和操作步骤？你的意思是自动程序在跑的同时，电脑端小程序也是开着的，然后下单成功之后，小程序那边直接会弹出二维码，然后手机直接扫码支付？
> > 
> > 
> > exactly
> 
> 您好，请问是您运行作者的程序时，您的pc端微信小程序一直是停留在购物车页面吗？然后会自动到结算--提交订单--弹出付款二维码吗？

任意页面都可以，只要开着就行，抢到后直接去待支付那里就行
