### ISSUE TITLE
提交订单失败,当前下单总金额：13.90 失败:前方拥挤，请稍后再试...

### ISSUE THREAD

**Issue by yexp** [JannsenYang/dingdong-helper#176]
手机下单成功，电脑下单不成功，电脑被封控了吗？

打印信息如下：
勾选购物车全选按钮失败:出现此问题有三个可能 1.偶发，无需处理 2.一个账号一天只能下两单  3.不要长时间运行程序，目前已知有人被风控了，暂时未确认风控的因素是ip还是用户或设备相关信息，如果要测试用单次执行模式，并发只能用于6点、8点半的前一分钟，然后执行时间不能超过2分钟，如果买不到就不要再执行程序了，切忌切忌
405问题解决方案，不保证完全有效,退出App账号重新登录，尝试刷新购物车和提交订单是否正常，如果正常退出小程序重新登录后再抓包，替换UserConfig中的cookie和device_token。
更新购物车数据成功,订单金额：13.90
更新配送时间成功
更新订单确认信息成功
提交订单失败,当前下单总金额：13.90 失败:前方拥挤，请稍后再试...

**Comment by LeeInChrist** [comment]
你的解决了吗？我从一开始抢都是这样的提示。
