### ISSUE TITLE
小程序已经更新到2.85.1了，还能使用吗？

### ISSUE THREAD

**Issue by xiangqian122** [JannsenYang/dingdong-helper#189]

**Comment by xiangqian122** [comment]
![image](https://user-images.githubusercontent.com/75673712/164757745-89af17f8-bd03-4001-b639-08bb877b1e38.png)

**Comment by Gumilton** [comment]
抓不到详细的API了，DD重新封装了。看起来好像是没戏了？

**Comment by amengll** [comment]
我三天前配置好的今天（4.23早六点场）还可以用，朋友昨天配置好的一直都是前方拥挤。还有另外一个昨晚配置好的，刚好卡在DD小程序更新之前，刚开始没问题，但是后来userconfig已经跑不通了，没有默认地址，后来重新抓包也没有抓到API信息了。

**Comment by CivelXu** [comment]
用不了了 叮咚真的是玩不起了

**Comment by shuangmei** [comment]
可以抓得到，换接口了，获取这些数据了

**Comment by shuangmei** [comment]
但是我今天早上在跑程序时，发现提示我重新登录，好像这cookie有时间限制了，具体是多久还不清楚

**Comment by misssssssE** [comment]
换接口了 
这个https://maicai.api.ddxq.mobi 已经没有了

”hello ! what are you 干啥呢“
感觉说话口气很冲

**Comment by haipengzzz** [comment]
可以看一下，这个host的抓包信息。gw.api.ddxq.mobi

**Comment by zhiiuuu** [comment]
嘻嘻 4月23号 早上8点半 下单成功 来感谢一下☺️

**Comment by Miles0928** [comment]
> 嘻嘻 4月23号 早上8点半 下单成功 来感谢一下relaxed

今天不是不能用了吗？

**Comment by Miles0928** [comment]
> 可以看一下，这个host的抓包信息。gw.api.ddxq.mobi

这个确实能抓包，但是运力检测以及更新订单都是显示拥挤

**Comment by wwnnrr** [comment]
包是可以拿到的，拿 不到，可以网上查一下，关于小程序不能拿包的问题，把Runtime目录删除就可以了。只是超过2分钟非常大可能封账号，我这边感觉是超过2分钟后，会出现405，这是程序会显示很长的一段话，然后就是查询新派送时间，一直显示拥堵。即使关闭程序，手动也是如此，我判断这就是封账号了。

**Comment by zhoujoshua** [comment]
> 包是可以拿到的，拿 不到，可以网上查一下，关于小程序不能拿包的问题，把Runtime目录删除就可以了。只是超过2分钟非常大可能封账号，我这边感觉是超过2分钟后，会出现405，这是程序会显示很长的一段话，然后就是查询新派送时间，一直显示拥堵。即使关闭程序，手动也是如此，我判断这就是封账号了。

请问Runtime目录在哪里？

**Comment by amengll** [comment]
> 可以看一下，这个host的抓包信息。gw.api.ddxq.mobi

在这个包里没有找到address id，你能找到吗？其他的都有

**Comment by amengll** [comment]
> 可以抓得到，换接口了，获取这些数据了

请问换了哪个接口？

**Comment by misssssssE** [comment]
> > 可以看一下，这个host的抓包信息。gw.api.ddxq.mobi
> 
> 在这个包里没有找到address id，你能找到吗？其他的都有

address id 的接口没有改吧

**Comment by AlisaQiu** [comment]
> 我三天前配置好的今天（4.23早六点场）还可以用，朋友昨天配置好的一直都是前方拥挤。还有另外一个昨晚配置好的，刚好卡在DD小程序更新之前，刚开始没问题，但是后来userconfig已经跑不通了，没有默认地址，后来重新抓包也没有抓到API信息了。

有一样的问题，说是找不到默认地址！

**Comment by amengll** [comment]
> > > 可以看一下，这个host的抓包信息。gw.api.ddxq.mobi
> > 
> > 
> > 在这个包里没有找到address id，你能找到吗？其他的都有
> 
> address id 的接口没有改吧

就是想如果要换地址帮别人下单怎么办

**Comment by zhiiuuu** [comment]
> > 嘻嘻 4月23号 早上8点半 下单成功 来感谢一下relaxed
> 
> 今天不是不能用了吗？

没有啊 我的确抢成功了

**Comment by Miles0928** [comment]
> > > 嘻嘻 4月23号 早上8点半 下单成功 来感谢一下relaxed
> > 
> > 今天不是不能用了吗？
> 
> 没有啊 我的确抢成功了

你用的是最新版程序吗？

**Comment by amengll** [comment]
gw.api.ddxq.mobi这个包可以找到其他的信息 但就是没有address_id

**Comment by happytogether** [comment]
> > > 嘻嘻 4月23号 早上8点半 下单成功 来感谢一下relaxed
> > 
> > 
> > 今天不是不能用了吗？
> 
> 没有啊 我的确抢成功了

是用有签名的版本吗？

**Comment by zhiiuuu** [comment]
> > > > 嘻嘻 4月23号 早上8点半 下单成功 来感谢一下relaxed
> > > 
> > > 
> > > 今天不是不能用了吗？
> > 
> > 
> > 没有啊 我的确抢成功了
> 
> 是用有签名的版本吗？

代码是最新的 小程序是什么版本我没看 电脑不知道在哪看

**Comment by Evergreen0726** [comment]
> > 包是可以拿到的，拿 不到，可以网上查一下，关于小程序不能拿包的问题，把Runtime目录删除就可以了。只是超过2分钟非常大可能封账号，我这边感觉是超过2分钟后，会出现405，这是程序会显示很长的一段话，然后就是查询新派送时间，一直显示拥堵。即使关闭程序，手动也是如此，我判断这就是封账号了。
> 
> 请问Runtime目录在哪里？

同问

**Comment by OccO3** [comment]
> > > 包是可以拿到的，拿 不到，可以网上查一下，关于小程序不能拿包的问题，把Runtime目录删除就可以了。只是超过2分钟非常大可能封账号，我这边感觉是超过2分钟后，会出现405，这是程序会显示很长的一段话，然后就是查询新派送时间，一直显示拥堵。即使关闭程序，手动也是如此，我判断这就是封账号了。
> > 
> > 
> > 请问Runtime目录在哪里？
> 
> 同问

runtime目录在哪里 大神@wwnnrr
