### ISSUE TITLE
全选购物车接口 405

### ISSUE THREAD

**Issue by ProdigalWang** [JannsenYang/dingdong-helper#193]
https://maicai.api.ddxq.mobi/cart/allCheck

{"error":"AssertError","code":"405","data":"-405"})

**Comment by ProdigalWang** [comment]
> 勾选购物车全选按钮失败:出现此问题有三个可能 1.偶发，无需处理 2.一个账号一天只能下两单  3.不要长时间运行程序，目前已知有人被风控了，暂时未确认风控的因素是ip还是用户或设备相关信息，如果要测试用单次执行模式，并发只能用于6点、8点半的前一分钟，然后执行时间不能超过2分钟，如果买不到就不要再执行程序了，切忌切忌
405问题解决方案，不保证完全有效,退出App账号重新登录，尝试刷新购物车和提交订单是否正常，如果正常退出小程序重新登录后再抓包，替换UserConfig中的cookie和device_token。
更新购物车数据成功,订单金额：177.00
无可选的配送时间 


这个是被封了还是没封？

**Comment by good1357** [comment]
> > 勾选购物车全选按钮失败:出现此问题有三个可能 1.偶发，无需处理 2.一个账号一天只能下两单  3.不要长时间运行程序，目前已知有人被风控了，暂时未确认风控的因素是ip还是用户或设备相关信息，如果要测试用单次执行模式，并发只能用于6点、8点半的前一分钟，然后执行时间不能超过2分钟，如果买不到就不要再执行程序了，切忌切忌
> > 405问题解决方案，不保证完全有效,退出App账号重新登录，尝试刷新购物车和提交订单是否正常，如果正常退出小程序重新登录后再抓包，替换UserConfig中的cookie和device_token。
> > 更新购物车数据成功,订单金额：177.00
> > 无可选的配送时间
> 
> 这个是被封了还是没封？

应该是风控，第一次24小时，第二次3天，第三期就长期了

**Comment by ProdigalWang** [comment]
> > > 勾选购物车全选按钮失败:出现此问题有三个可能 1.偶发，无需处理 2.一个账号一天只能下两单  3.不要长时间运行程序，目前已知有人被风控了，暂时未确认风控的因素是ip还是用户或设备相关信息，如果要测试用单次执行模式，并发只能用于6点、8点半的前一分钟，然后执行时间不能超过2分钟，如果买不到就不要再执行程序了，切忌切忌
> > > 405问题解决方案，不保证完全有效,退出App账号重新登录，尝试刷新购物车和提交订单是否正常，如果正常退出小程序重新登录后再抓包，替换UserConfig中的cookie和device_token。
> > > 更新购物车数据成功,订单金额：177.00
> > > 无可选的配送时间
> > 
> > 
> > 这个是被封了还是没封？
> 
> 应该是风控，第一次24小时，第二次3天，第三期就长期了

如果是风控的话，这个号是不是不需要抢了？一定会抢不到？

**Comment by good1357** [comment]
> > > > 勾选购物车全选按钮失败:出现此问题有三个可能 1.偶发，无需处理 2.一个账号一天只能下两单  3.不要长时间运行程序，目前已知有人被风控了，暂时未确认风控的因素是ip还是用户或设备相关信息，如果要测试用单次执行模式，并发只能用于6点、8点半的前一分钟，然后执行时间不能超过2分钟，如果买不到就不要再执行程序了，切忌切忌
> > > > 405问题解决方案，不保证完全有效,退出App账号重新登录，尝试刷新购物车和提交订单是否正常，如果正常退出小程序重新登录后再抓包，替换UserConfig中的cookie和device_token。
> > > > 更新购物车数据成功,订单金额：177.00
> > > > 无可选的配送时间
> > > 
> > > 
> > > 这个是被封了还是没封？
> > 
> > 
> > 应该是风控，第一次24小时，第二次3天，第三期就长期了
> 
> 如果是风控的话，这个号是不是不需要抢了？一定会抢不到？

是的，不建议这个账号再反复尝试，静止三天，这三天用其他账户，btw，重启下上网的猫，非家里路由器，IP138查一下确认自己的外网IP变掉。

**Comment by ProdigalWang** [comment]
https://github.com/JannsenYang/dingdong-helper/issues/207#issue-1213718215 
可尝试换agent解决
