### ISSUE TITLE
你好， 请问能具体和我说明下使用方法么？ 这个程序是在手机端还是电脑端跑的， 能加个v么？

### ISSUE THREAD

**Issue by DancingLeaf123** [JannsenYang/dingdong-helper#2]
v  dancingleaf123
刚开始学用fildder

**Comment by JannsenYang** [comment]
电脑上跑的   但是需要通过抓包工具抓手机上微信叮咚小程序里的token信息  购物车里的商品自己加 时间一到秒下单 自己去待支付订单里支付就可以了

**Comment by DancingLeaf123** [comment]
你好， 我刚刚成功抓取了那些token，也填进去了， 不过run起来提示
“开始获取收货人信息
用户信息失效，请确保UserConfig参数准确，并且微信上的叮咚小程序不能退出登录
addressId：null”
我确认我的小程序是开着的， 以及每次重新登录需要更新token信息么

**Comment by DancingLeaf123** [comment]
成功了成功了， 刚才似乎是填错cookie了
