### ISSUE TITLE
全选和提交订单405

### ISSUE THREAD

**Issue by kzli** [JannsenYang/dingdong-helper#203]
用了最新的加密，全选和提交订单一直405，换个账号也是这样，切换地址到杭州后app可以下单支付，重新抓包杭州的定位后全选和提交订单也还是405。。。。
{"code":"405","data":"-405","error":"AssertError"}

**Comment by kzli** [comment]
换账号和重启路由器device_token也没变，你们是这样吗

**Comment by IceCd1996** [comment]
同上，换账号和重启路由器device_token也没变，而且小程序商品页面刷不出来了，一直显示加载中。

**Comment by kzli** [comment]
x
