### ISSUE TITLE
提交订单失败

### ISSUE THREAD

**Issue by oiin** [JannsenYang/dingdong-helper#206]
![image](https://user-images.githubusercontent.com/88411797/164980210-07c9834c-24f0-44c6-9927-54959c71ac57.png)
![image](https://user-images.githubusercontent.com/88411797/164980306-c169b44b-9c2e-436f-9e41-40938be8b7db.png)

测试地址是杭州能买菜，能配送的地方
1】账号未风控
pc小程序、手机app均可以手动正常下单，但是跑程序就出现【提交订单失败】

2】重启猫更换ip尝试过，注册新号尝试过，退出重新登录尝试过
3】因为每次重新登录，device_token和ddmc-device-id参数值都不变，所以瞎改这两个参数值，也尝试过
4】看有些请求里面的heards里面有ddmc-sdkversion这个参数，感觉像是新加的，所以自己在heards里面也试着加了这个参数如下图，也没用
![image](https://user-images.githubusercontent.com/88411797/164981090-f537f859-1c5c-4187-98a8-59105024ee86.png)

上面所有的尝试，不管改前改后，最后结果都是相同的【提交订单失败】

请求好心大佬匡扶正义消灭黑暗，传道受业解惑，拯救一下小白脆弱的心灵！

期待光的出现......

**Comment by ssssimplesss** [comment]
和你一样，老哥解决了说一下

**Comment by happytogether** [comment]
#207
