### ISSUE TITLE
我不知道你为什么开源

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [JannsenYang/dingdong-helper#239]
我不知道你为什么开源，被官方盯上了，导致我这边程序还得想办法改，越过风控，自己偷偷用不行吗，发出来干嘛，为了虚荣心？

**Comment by LeiZhang-Hunter** [comment]
本来我逆向了一遍叮咚安卓的app，你大张旗鼓的发到网上；算了，我也不会再去逆向叮咚的安卓app了，成本越来越高，为了这个事情也不值得，这本来就不是合法的事情，你还发到网上，真的自己不想用就算了，还影响其他人，导致我这些不开源的都受到了间接影响

**Comment by igwen6w** [comment]
开源是送死行为，还把其他兄弟给捎带了，不过现阶段也不需要抢菜了，运力慢慢恢复了，买菜啥的还是挺简单的

**Comment by LeiZhang-Hunter** [comment]
> 开源是送死行为，还把其他兄弟给捎带了，不过现阶段也不需要抢菜了，运力慢慢恢复了，买菜啥的还是挺简单的
我逆向安卓app花了3天，为了买个菜我再去搞3天？本来不开源很少人愿意和有能力写脚本，也不会引起官方关注，导致我现在买个黄瓜都费劲，总不能再去花一周去逆向他的app吧，你的star是多了，我们再也不能在线上轻松的买菜了

**Comment by LeiZhang-Hunter** [comment]
算了，祝你好运，事情就这样了

**Comment by bill020** [comment]
你这人思路有问题！人家至少帮助了很多人！而不像你这么狭隘只想着自己
至少我还用这个帮抢不到菜的老人买过2次菜
纯粹看不过来留个言！

**Comment by LeiZhang-Hunter** [comment]
> 你这人思路有问题！人家至少帮助了很多人！而不像你这么狭隘只想着自己 至少我还用这个帮抢不到菜的老人买过2次菜 纯粹看不过来留个言！

我这么晚了开电脑来回答你这个自私的人

**Comment by LeiZhang-Hunter** [comment]
> 你这人思路有问题！人家至少帮助了很多人！而不像你这么狭隘只想着自己 至少我还用这个帮抢不到菜的老人买过2次菜 纯粹看不过来留个言！

1、上海有2500w人，运力有限，如果这个程序有2000人在用，就意味着有2000正常的人抢不到，导致合法路子的人抢不到菜
2、爬虫本就违法，这还是什么光彩的事
3、代码在叮咚工程师手里，你把代码发出来，第二天他们就会想到解决方案
4、发出来就是为了虚荣心，为了star，觉得自己牛逼，其实这真的很愚蠢，很傻，损人不利己，导致其他不开源的也抢不到了
我不知道你为什么觉得这是伟大，这就是损人不利己的虚荣

**Comment by LeiZhang-Hunter** [comment]
我也不想网暴，但这事就这样了，也没必要在说什么了，一些不光彩的事，渗透、违法的事情，自己偷着用用就行了

**Comment by IMLR** [comment]
插👀，特来围观

**Comment by cxjnevergiveup** [comment]
> 我也不想网暴，但这事就这样了，也没必要在说什么了，一些不光彩的事，渗透、违法的事情，自己偷着用用就行了
> 
> 

你马死了啊 在这里狗叫什么 影响你赚钱了？

**Comment by coldtea07** [comment]
> 在用

你这逻辑笑死我了， 2000人在用 和几个人在用有什么区别？不都影响了正常人抢菜？  你自己不就是为了这种不公平的抢菜去逆向？按你的说法，你自己都没道德在这站在道德至高点上BB，脑袋被门夹了？如果照你这么说，代码被叮咚看到了修复了 反而公平不是好事？ 说到底不就是因为影响你使用了你才乱喷一通，真是巨婴一个

**Comment by kdtheodore35** [comment]
气急败坏？？？
你不是蠢的话，那就是坏

**Comment by wwnnrr** [comment]
> > 你这人思路有问题！人家至少帮助了很多人！而不像你这么狭隘只想着自己 至少我还用这个帮抢不到菜的老人买过2次菜 纯粹看不过来留个言！
> 
> 1、上海有2500w人，运力有限，如果这个程序有2000人在用，就意味着有2000正常的人抢不到，导致合法路子的人抢不到菜 2、爬虫本就违法，这还是什么光彩的事 3、代码在叮咚工程师手里，你把代码发出来，第二天他们就会想到解决方案 4、发出来就是为了虚荣心，为了star，觉得自己牛逼，其实这真的很愚蠢，很傻，损人不利己，导致其他不开源的也抢不到了 我不知道你为什么觉得这是伟大，这就是损人不利己的虚荣

你这个大晚上开电脑回信息，手机也可以的，如果说你从来不写这类代码，不去抢菜，写这个也就算了，就算你去举报也没什么，但似乎你做的比人家更过分，都逆向分析了，还举报就不好了，我拿到代码用过，封过，从来没抢到过，但还是感谢分享，因为抢不抢得到已经不重要了，重要的是让我学习了一把JAVA，js，分享出来比你躲在背后偷乐强多了。

> > 你这人思路有问题！人家至少帮助了很多人！而不像你这么狭隘只想着自己 至少我还用这个帮抢不到菜的老人买过2次菜 纯粹看不过来留个言！
> 
> 我这么晚了开电脑来回答你这个自私的人

你这个大晚上开电脑回信息，手机也可以的，如果说你从来不写这类代码，不去抢菜，写这个也就算了，就算你去举报也没什么，但似乎你做的比人家更过分，都逆向分析了，还举报就不好了，我拿到代码用过，封过，从来没抢到过，但还是感谢分享，因为抢不抢得到已经不重要了，重要的是让我学习了一把JAVA，js，分享出来比你躲在背后偷乐强多了。

**Comment by LeiZhang-Hunter** [comment]
> > 在用
> 
> 你这逻辑笑死我了， 2000人在用 和几个人在用有什么区别？不都影响了正常人抢菜？ 你自己不就是为了这种不公平的抢菜去逆向？按你的说法，你自己都没道德在这站在道德至高点上BB，脑袋被门夹了？如果照你这么说，代码被叮咚看到了修复了 反而公平不是好事？ 说到底不就是因为影响你使用了你才乱喷一通，真是巨婴一个

收不收钱有什么利益我不管，但是做渗透、爬虫就是要藏着，而不是满世界宣传，让叮咚那群工程师去不漏洞，这丝毫没有意义，他们一次次修了漏洞对谁有好处，免费帮叮咚找bug?不开源的话他们可能要过半个月才发现，开源了立马就发现！！为什么不藏着，反而公开出来？

**Comment by iu159** [comment]
疯狗乱吠，你自己是正常抢的不？发情了没地方发泄找小区母狗啊，sb

**Comment by iu159** [comment]
人家是好人，在你这成啥了。心眼小的哦，针都穿不过

**Comment by iu159** [comment]
优美的中国话，cnmb，nmsl

**Comment by iu159** [comment]
你妈是不是给狗干的你

**Comment by iu159** [comment]
你妈是不是给狗干生的你

**Comment by LeiZhang-Hunter** [comment]
> 你妈是不是给狗干生的你

工程师要注意保护自己，而不是开源出来，给一群不是很懂的小白去用；如果这是合法的项目那我祝福你；但是爬虫本来就违法，还公布出来，这不是把自己的身体暴露在敌方的炮火下？帮dingdong打工？、

**Comment by zric** [comment]
咋的 只有你能用 别人不能？什么逻辑

**Comment by LeiZhang-Hunter** [comment]
> 咋的 只有你能用 别人不能？什么逻辑

想用的话 你可以自己去写呀，对不对，为啥非要发到网上，被官方盯上呢？

**Comment by LeiZhang-Hunter** [comment]
> 咋的 只有你能用 别人不能？什么逻辑

你为什么get不到我的重点，我的意思是不要被官方发现
