### ISSUE TITLE
大兄弟，美团抢菜的啥时候能搞一个？

### ISSUE THREAD

**Issue by liaomengge** [JannsenYang/dingdong-helper#35]

**Comment by JannsenYang** [comment]
之前搞过美团外卖的  挺复杂的  也不是绝对搞不定 应该还是有点可能性的  但是我没动力 我所在地区没有美团买菜 抱歉。。

**Comment by peterkcwu** [comment]
> 之前搞过美团外卖的 挺复杂的 也不是绝对搞不定 应该还是有点可能性的 但是我没动力 我所在地区没有美团买菜 抱歉。。

大神有没有盒马团购的？
