### ISSUE TITLE
订单有了，失败到支付上了！

### ISSUE THREAD

**Issue by WCQ2022** [JannsenYang/dingdong-helper#37]
高峰期支付也限流，支付权限估计不好获取吧？这个有没有什么解决方案？？

**Comment by JannsenYang** [comment]
你是今天首单还是已经下过单了  别人并且有多人反馈一个账号一天只能下两单  第三单要么无法下单 要么不能支付

**Comment by 18516557809** [comment]
第二单无法支付

**Comment by WCQ2022** [comment]
早上6点的时候第一次用，可以支付。然后8.30的时候提示支付人数多

**Comment by WCQ2022** [comment]
账号看上去没什么异常。封号应该能看出来吧

**Comment by JannsenYang** [comment]
那应该问题不大 明天再试吧  可以肯定的是叮咚对下单做了限制 我人工操作也下不了第三单 具体服务器的逻辑非内部人士也不可能知道

**Comment by WCQ2022** [comment]
好的。明天再看！谢谢了，很有用！
