### ISSUE TITLE
userconfig跑完后， 跑application 是我哪里操作错了么？提示“请先执行UserConfig获取配送地址id”

### ISSUE THREAD

**Issue by DancingLeaf123** [JannsenYang/dingdong-helper#4]
我已经跑成功userconfig了

**Comment by DancingLeaf123** [comment]
以及你能加我一个vx么， 我可能对java不熟悉导致了这个问题

**Comment by ChenCyl** [comment]
> 我已经跑成功userconfig了

@DancingLeaf123 hello 跑完之后要把addressid填到userconfig.java里哦 有填吗
