### ISSUE TITLE
捡漏模式下不能一直运行

### ISSUE THREAD

**Issue by wJDKnight** [JannsenYang/dingdong-helper#43]
为了捡漏，间隔时间调整发现bug。Application.java 12行
`            Thread.sleep(100);`
应为
`            Thread.sleep(millis);`

我把并发和间隔时间设置好了之后，发现运行了一小会程序就停了。我把Api.java 193行的
`Application.map.put("end", new HashMap<>());`
注释掉了。 

不知道这样做会不会有什么问题。

**Comment by JannsenYang** [comment]
更新代码 新增Sentinel哨兵模式
