### ISSUE TITLE
windows 抓包不了

### ISSUE THREAD

**Issue by Liejiu946** [JannsenYang/dingdong-helper#45]
你好，windows 可以用吗 为啥我老是抓不了包 我用了charles 和 fiddler都抓不了

**Comment by cxjnevergiveup** [comment]
> 

你好 我这会抓包 但是java不熟悉 互相交流一下？ wechat：zyyds_2021

**Comment by wJDKnight** [comment]
我用windows可以抓包，用法和他给的那个mac的教程差不多的呀

**Comment by Liejiu946** [comment]
> 我用windows可以抓包，用法和他给的那个mac的教程差不多的呀

加我微信13024112097 帮帮忙帖子

**Comment by qfmy92** [comment]
https://wx.m.ddxq.mobi/ 不谢

**Comment by LxzBUG** [comment]
苹果手机直接就能抓

**Comment by hahalila** [comment]
ios用steam抓包
windows用fiddler抓包

**Comment by zhoujieming2020** [comment]
手机端直接抓的，用的小黄鸟

**Comment by Liejiu946** [comment]
> https://wx.m.ddxq.mobi/ 不谢
