### ISSUE TITLE
yang大神 请问我这样导入代码对嘛 左下角的报错是怎么回事呀 请求您的帮助 快饿死了！

### ISSUE THREAD

**Issue by cxjnevergiveup** [JannsenYang/dingdong-helper#47]
![Uploading 微信图片_20220412213640.png…]()

**Comment by JannsenYang** [comment]
看不见你的图  项目是最简单结构的maven项目 写java的应该都能运行 如果不是搞java的建议找个会java的好友帮一下忙 很简单

**Comment by cxjnevergiveup** [comment]
> 看不见你的图 项目是最简单结构的maven项目 写java的应该都能运行 如果不是搞java的建议找个会java的好友帮一下忙 

请问在在ide里是选择那个maven创建项目吗  我配了jdk的环境 maven是不是要配环境的？

**Comment by JannsenYang** [comment]
你如果用的是idea 直接导入项目就行了（file-open-项目文件夹） idea会判断这是个maven项目 会自动构建的 等右下角进度条好了 就可以执行了

**Comment by JannsenYang** [comment]
idea自带maven 你可以不用安装maven 用自带的

**Comment by cxjnevergiveup** [comment]
<img width="834" alt="微信图片_20220412225256" src="https://user-images.githubusercontent.com/52702777/162990920-f243f459-e74c-47bf-9213-883b6f06ced8.png">

**Comment by cxjnevergiveup** [comment]
> idea自带maven 你可以不用安装maven 用自带的

<img width="834" alt="微信图片_20220412225256" src="https://user-images.githubusercontent.com/52702777/162991025-2efebe33-60c3-4705-a0ab-958dda1f6543.png">

我这样子对吗 哥哥 下面的报错怎么解决啊 搞一晚上了  。。。。救救我

**Comment by SnoopyGo** [comment]
> > idea自带maven 你可以不用安装maven 用自带的
> 
> <img alt="微信图片_20220412225256" width="834" src="https://user-images.githubusercontent.com/52702777/162991025-2efebe33-60c3-4705-a0ab-958dda1f6543.png">
> 
> 我这样子对吗 哥哥 下面的报错怎么解决啊 搞一晚上了 。。。。救救我
缺少依赖，你maven reload一下

**Comment by JannsenYang** [comment]
你不要自己建项目再丢文件进去  而且你的版本也比较老了 有bug  你重新下载一下项目 用idea - file - open 选择文件夹 应该是什么都不用做 idea自动就会当maven项目处理

**Comment by cxjnevergiveup** [comment]
> 你不要自己建项目再丢文件进去 而且你的版本也比较老了 有bug 你重新下载一下项目 用idea - file - open 选择文件夹 应该是什么都不用做 idea自动就会当maven项目处理

大佬 我丢进去了 
<img width="834" alt="微信图片_20220412232133" src="https://user-images.githubusercontent.com/52702777/162997213-51593e4a-678d-40f5-be0d-fe29ba96523a.png">
接下来怎么办啊 抓包我都会了 就差这个代码了 ！

**Comment by cxjnevergiveup** [comment]
> 你不要自己建项目再丢文件进去 而且你的版本也比较老了 有bug 你重新下载一下项目 用idea - file - open 选择文件夹 应该是什么都不用做 idea自动就会当maven项目处理

请问能留个wechat嘛  教我一下呗 小弟红包答谢

**Comment by MableUsher** [comment]
> > 你不要自己建项目再丢文件进去 而且你的版本也比较老了 有bug 你重新下载一下项目 用idea - file - open 选择文件夹 应该是什么都不用做 idea自动就会当maven项目处理
> 
> 请问能留个wechat嘛 教我一下呗 小弟红包答谢

git clone 下来，maven build看报错信息，依赖红多半是setting文件的问题，去网上抄一份就行了

**Comment by cxjnevergiveup** [comment]
已解决谢谢
