### ISSUE TITLE
各路大神 运行UserConfig时控制台返回乱码 怎么解决 救救孩子把

### ISSUE THREAD

**Issue by cxjnevergiveup** [JannsenYang/dingdong-helper#49]

**Comment by cxjnevergiveup** [comment]
<img width="939" alt="微信图片_20220413002939" src="https://user-images.githubusercontent.com/52702777/163010140-8bd21454-680a-4d2d-a5e1-bc76a4b00e14.png">

编码格式全都改成UTF-8了
<img width="939" alt="微信图片_20220413002939" src="https://user-images.githubusercontent.com/52702777/163010271-acae2f0b-3770-4660-83bf-2a6b6972b2b1.png">

**Comment by zhoujieming2020** [comment]
试试看
![Uploading mmexport1649783811009.png…]()

**Comment by zhoujieming2020** [comment]
![Uploading mmexport1649783811009.png…]()

**Comment by zhoujieming2020** [comment]
图传不上

**Comment by cxjnevergiveup** [comment]
> 图传不上
怎么操作啊 哥

**Comment by 52znn** [comment]
jdk换成17版本https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.msi

**Comment by cxjnevergiveup** [comment]
已解决谢谢

**Comment by skOak** [comment]
乱码问题，最后参考了下面的文章解决了。
https://juejin.cn/post/6844904008625160206

**Comment by xuanskyer** [comment]
![image](https://user-images.githubusercontent.com/3071881/163660501-acc69050-5b00-4208-bc13-3fe172d244d5.png)
.idea/encodings.xml 里直接改成GBK就可以了

**Comment by jason-ufo** [comment]
13370065911微信






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 凌晨1:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JannsenYang/dingdong-helper] 各路大神 运行UserConfig时控制台返回乱码 怎么解决 救救孩子把 (Issue #49)





  
图传不上
 怎么操作啊 哥
