### ISSUE TITLE
为什么提交下单的时候不需要填写nars跟sesi这俩，我之前一直想不通这俩参数的生成规则

### ISSUE THREAD

**Issue by cwh1022** [JannsenYang/dingdong-helper#53]
作者老哥，能否解释下你是怎么发现不填写这俩参数也能提交成功的啊，别告诉我你抓包的时候没有这俩参数

**Comment by JannsenYang** [comment]
看到参数以为是签名 也准备去找签名的代码  但是去掉参数发了个请求能发成功  我估计应该是没做完 后面有可能会完善
