### ISSUE TITLE
拿别的城市试了一下，购物车有货物，也打开全选了，显示无可买的商品

### ISSUE THREAD

**Issue by csuXinda** [JannsenYang/dingdong-helper#54]

**Comment by JannsenYang** [comment]
headers和body中citynumber参数替换了没有   收货地址要改成默认 执行UserConfig确认站点信息是否正确

**Comment by cxjnevergiveup** [comment]
> headers和body中citynumber参数替换了没有   收货地址要改成默认 执行UserConfig确认站点信息是否正确

大佬 我换了杭州没有改userconfig里的citynumber 竟然也可以下单 只改了addressid和stationid这两个
