### ISSUE TITLE
单次执行模式 和 高峰期策略的切换要调整哪部分代码呢？ 我看你注释了单次模式

### ISSUE THREAD

**Issue by DancingLeaf123** [JannsenYang/dingdong-helper#6]

**Comment by JannsenYang** [comment]
单次是用来测试是否可以下单的  不做实际用途  如果单次能成功 你自己手点也能成功  主要是在开放购买比如早上6点和8点半的时候在高峰期通过大量的并发请求绕过叮咚服务器的限流算法

**Comment by binkundai** [comment]
第一次接触java，根据搜索来的信息购物车放了一个白酒测试成功了，请问高峰期策略是自动的还是需要在程序里面做手动调整的？谢谢

![image](https://user-images.githubusercontent.com/97794686/162607641-092fe11f-a388-42a4-bdfb-eb66a4e79f5b.png)
