### ISSUE TITLE
更新购物车数据失败:当前人多拥挤，请稍后尝试刷新页面

### ISSUE THREAD

**Issue by wJDKnight** [JannsenYang/dingdong-helper#62]
连续两天没抢到菜了，饿啊。。
两个号，线程数分别设为4，6，都不行
这个是因为网不好吗

**Comment by JannsenYang** [comment]
一直持续性的吗 我这边提前30秒执行  大概持续10秒就成功了 6点一到就开始下单了

**Comment by wJDKnight** [comment]
> 一直持续性的吗 我这边提前30秒执行 大概持续10秒就成功了 6点一到就开始下单了

是的。不过我小程序叮咚的购物车也是刷不出来，但是手机app可以刷出来

**Comment by wJDKnight** [comment]
code有时是405有时是-3000

**Comment by JannsenYang** [comment]
设置个杭州的地址跑一个测试下单试试  如果不能下可能就是号被封了 根据反馈有些号第二天就可以买了 不要长时间高并发跑 会有影响 新版本加入了保护程序 只要不改代码应该不会再出现了 如果想捡漏有个单线程间隔时间长的哨兵模式可以一直运行

**Comment by wJDKnight** [comment]
看样子是，我又换了个号就可以。
谢谢
