### ISSUE TITLE
测试了一下 购物车是有东西的，一直提示都是购物车无可购买商品

### ISSUE THREAD

**Issue by dingjingyu** [JannsenYang/dingdong-helper#7]
测试了一下 购物车是有东西的，一直提示都是购物车无可购买商品

**Comment by JannsenYang** [comment]
把Api中getCart方法里  String body = httpRequest.execute().body();   这个body输出一下 把body贴出来我看一下

**Comment by dingjingyu** [comment]
现在购物车那个正常了，但是下单可约时间 json 

> 

> ### 数据中拉出来的全是已约满，但是小程序是可以选择的

**Comment by JannsenYang** [comment]
那打印一下getMultiReserveTime 中 String body = httpRequest.execute().body();  这个是获取配送信息的  如果自己找不到问题发出来我看一下

**Comment by dingjingyu** [comment]
这个是购物车的数据
`{
	"success": true,
	"code": 0,
	"msg": "success",
	"data": {
		"product": {
			"effective": [],
			"invalid": [{
				"products": [{
					"id": "609a4060899093cb1f5a6915",
					"type": 0,
					"category": "",
					"price": "13.90",
					"sizes": [],
					"count": 1,
					"status": 0,
					"gifts": [],
					"addTime": 1649568807,
					"cart_id": "609a4060899093cb1f5a6915",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "596,1289,1292",
					"origin_price": "13.90",
					"size_price": "0.00",
					"add_price": "13.90",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "展艺硅胶雪糕模（草莓+西瓜）2个/组",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/9368ad10dbc441620696664913.jpg?width=800&height=800",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "200",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_fresh_food": 0
				}, {
					"id": "5e8eebcd7cdbf013083016dd",
					"type": 0,
					"category": "58fbf4bf936edfe3568b5990",
					"price": "9.50",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649568385,
					"cart_id": "5e8eebcd7cdbf013083016dd",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "58f9d213936edfe4568b569a,58fbf4bf936edfe3568b5990",
					"manage_category_path": "13,1184,1190",
					"origin_price": "9.50",
					"size_price": "0.00",
					"add_price": "9.50",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "崇明西葫芦 350g/份",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/66de071d1afb51587521029608.jpg!deliver.product.list",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "350",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_fresh_food": 0
				}, {
					"id": "5f55fd49f06606002c49a513",
					"type": 0,
					"category": "58fb414c936edf88198b5970",
					"price": "468.00",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649568385,
					"cart_id": "5f55fd49f06606002c49a513",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "58f9e5c4936edfe4568b5793,58fb414c936edf88198b5970",
					"manage_category_path": "411,412,413",
					"origin_price": "468.00",
					"size_price": "0.00",
					"add_price": "468.00",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "剑南春52度白酒 500ml/瓶",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/98e1b4b5c95561599811743193.jpg!deliver.product.list",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "瓶",
					"net_weight": "500",
					"net_weight_unit": "ml",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_fresh_food": 0
				}, {
					"id": "60473bca47987eb75d42290f",
					"type": 0,
					"category": "",
					"price": "19.90",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649567799,
					"cart_id": "60473bca47987eb75d42290f",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "738,747,1278",
					"origin_price": "19.90",
					"size_price": "0.00",
					"add_price": "19.90",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "【净菜】蔡长青去皮春笋 150g",
					"product_type": 0,
					"small_image": "https://imgnew.ddimg.mobi/product/aeeb4142662b4f7f8cd365bda597c830.jpg?width=800&height=800",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "150",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 2,
					"temperature_layer": "0~4℃",
					"is_fresh_food": 0
				}, {
					"id": "611a04578537dbc9f1dd54a5",
					"type": 0,
					"category": "",
					"price": "22.80",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649566435,
					"cart_id": "611a04578537dbc9f1dd54a5",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "193,1026,1029",
					"origin_price": "22.80",
					"size_price": "0.00",
					"add_price": "22.80",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "冷冻黑虎虾仁 150g",
					"product_type": 0,
					"small_image": "https://ddfs-public.ddimg.mobi/img/blind/product-management/202108/721ce62e15ce4715938af033b2c86dc6.jpg?width=800&height=800",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "150",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 3,
					"temperature_layer": "-18℃以下",
					"is_fresh_food": 0
				}]
			}]
		},
		"toast": "",
		"alert": null,
		"all_activity_cart": [],
		"station_id": "610f3fd0b5871d00015f46aa",
		"order_product_list": [],
		"new_order_product_list": [],
		"order_product_list_sign": "d751713988987e9331980363e24189ce",
		"full_to_off": "39.00",
		"freight_money": "5.00",
		"free_freight_type": 99,
		"instant_rebate_money": "0.00",
		"goods_real_money": "0.00",
		"total_money": "0.00",
		"is_select_detail": 1,
		"good_max_count_toast": "订单商品明细行数超过最大限制，无法按商品明细开票",
		"is_all_check": 0,
		"onion_id": "",
		"onion_tip": {},
		"cart_notice": "满39.00元可免配送费",
		"cart_notice_new": "满39.00元可免配送费",
		"free_freight_notice": {},
		"cart_top_floor_info": [],
		"cart_count": 0,
		"total_count": 5,
		"product_num": {
			"609a4060899093cb1f5a6915": 1,
			"5f55fd49f06606002c49a513": 1,
			"60473bca47987eb75d42290f": 1,
			"611a04578537dbc9f1dd54a5": 1,
			"5e8eebcd7cdbf013083016dd": 1
		},
		"stop_order_toast": "",
		"gift_no_size_tip": "",
		"is_hit_onion": false,
		"onion_ab_config": 3,
		"is_hit_gift_size": true,
		"coupon_text_a": "",
		"coupon_text_b": "",
		"need_amount": "",
		"is_vip_ticket": 0,
		"coupon_amount": "",
		"coupon_state": -1,
		"coupon_type": 0,
		"next_recommend_coupon": {
			"coupon_text_a": null,
			"coupon_text_b": null,
			"need_amount": null,
			"is_vip_ticket": null,
			"is_common_ticket": null
		},
		"show_coupon_detail": false,
		"contains_advent_gift": 0,
		"parent_order_info": {
			"parent_order_sign": "d751713988987e9331980363e24189ce",
			"stockout_gift_product": [],
			"stockout_gift_text": "赠品赠完即止，不再补送，敬请谅解。",
			"is_open_presale_use_virtual_stock": false
		},
		"is_support_merge_payment": 1,
		"sodexo_nonsupport_product_list": [],
		"valid_product_counts": {}
	},
	"tradeTag": "success",
	"server_time": 1649569273,
	"is_trade": 1
}`

1. 我看了代码，进行debug 走的，能看懂，你的那个判断  new_order_product_list 这个确实是 0 但是为什么会是0 呢。
2. 关于预约时间，我从小程序上是可以预约的，订单也可以正常提交，但是 getMultiReserveTime 这个里面转为json 的可约时间数据全部都是已约满，于小程序上不符合（我能看懂代码，也会调试，说的是真的我这边的情况，请大哥帮忙分析下。现在又变成了购物车无可购买的，实际上那个酒是可以的）
3 qq:1450360226 如果方便，指导下呗。

**Comment by JannsenYang** [comment]
我大概率猜测是你站点id拿错了  看一下UserConfig中有一个station id  你抓包的时候那个站点可能是你公司的 这样会出现你说的这个问题 你重新进一下小程序 确认站点 然后再抓包 替换调stationid  注意 header和body中都有station id

**Comment by JannsenYang** [comment]
你手机上的站点是你家的  你抓包的站点是公司的 你手机上能看到配送时间和购物车 但是实际你跑的程序里是公司的站点 那个站点可能没有商品和配送了 如果不是这个问题你再回我 加你

**Comment by DancingLeaf123** [comment]
那请问， 倘若我要帮别人抢， 要切换站点 ， 除了address 和 station id 还有什么要改么？

**Comment by JannsenYang** [comment]
> 那请问， 倘若我要帮别人抢， 要切换站点 ， 除了address 和 station id 还有什么要改么？

如果你是用你自己的号帮别人抢，那么只需要改这两个。
如果你是想用别人的账号购买，那就是替换整个UserInfo里的数据。

**Comment by dingjingyu** [comment]
`{
	"success": true,
	"code": 0,
	"msg": "success",
	"data": {
		"product": {
			"effective": [{
				"activity_info": {
					"id": "",
					"gifts": null
				},
				"products": [{
					"id": "609a4060899093cb1f5a6915",
					"type": 0,
					"category": "",
					"price": "13.90",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649572728,
					"cart_id": "609a4060899093cb1f5a6915",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "596,1289,1292",
					"total_price": "13.90",
					"origin_price": "13.90",
					"no_supplementary_price": "13.90",
					"no_supplementary_total_price": "13.90",
					"size_price": "0.00",
					"add_price": "13.90",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "展艺硅胶雪糕模（草莓+西瓜）2个/组",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/9368ad10dbc441620696664913.jpg?width=800&height=800",
					"all_sizes": [],
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "200",
					"net_weight_unit": "g",
					"is_stock": false,
					"old_count": 1,
					"stock_number": 2,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_shared_station_product": 0,
					"is_fresh_food": 0,
					"accessory_gifts": [],
					"accessory_text": "",
					"supplementary_list": []
				}, {
					"id": "5f55fd49f06606002c49a513",
					"type": 0,
					"category": "58fb414c936edf88198b5970",
					"price": "468.00",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649572728,
					"cart_id": "5f55fd49f06606002c49a513",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "58f9e5c4936edfe4568b5793,58fb414c936edf88198b5970",
					"manage_category_path": "411,412,413",
					"total_price": "468.00",
					"origin_price": "468.00",
					"no_supplementary_price": "468.00",
					"no_supplementary_total_price": "468.00",
					"size_price": "0.00",
					"add_price": "468.00",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "剑南春52度白酒 500ml/瓶",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/98e1b4b5c95561599811743193.jpg!deliver.product.list",
					"all_sizes": [],
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "瓶",
					"net_weight": "500",
					"net_weight_unit": "ml",
					"is_stock": false,
					"old_count": 1,
					"stock_number": 1,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_shared_station_product": 0,
					"is_fresh_food": 0,
					"accessory_gifts": [],
					"accessory_text": "",
					"supplementary_list": []
				}]
			}],
			"invalid": [{
				"products": [{
					"id": "5e8eebcd7cdbf013083016dd",
					"type": 0,
					"category": "58fbf4bf936edfe3568b5990",
					"price": "9.50",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649568385,
					"cart_id": "5e8eebcd7cdbf013083016dd",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "58f9d213936edfe4568b569a,58fbf4bf936edfe3568b5990",
					"manage_category_path": "13,1184,1190",
					"origin_price": "9.50",
					"size_price": "0.00",
					"add_price": "9.50",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "崇明西葫芦 350g/份",
					"product_type": 0,
					"small_image": "https://img.ddimg.mobi/product/66de071d1afb51587521029608.jpg!deliver.product.list",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "350",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 0,
					"temperature_layer": "",
					"is_fresh_food": 0
				}, {
					"id": "60473bca47987eb75d42290f",
					"type": 0,
					"category": "",
					"price": "19.90",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649567799,
					"cart_id": "60473bca47987eb75d42290f",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "738,747,1278",
					"origin_price": "19.90",
					"size_price": "0.00",
					"add_price": "19.90",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "【净菜】蔡长青去皮春笋 150g",
					"product_type": 0,
					"small_image": "https://imgnew.ddimg.mobi/product/aeeb4142662b4f7f8cd365bda597c830.jpg?width=800&height=800",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "150",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 2,
					"temperature_layer": "0~4℃",
					"is_fresh_food": 0
				}, {
					"id": "611a04578537dbc9f1dd54a5",
					"type": 0,
					"category": "",
					"price": "22.80",
					"sizes": [],
					"count": 1,
					"status": 1,
					"gifts": [],
					"addTime": 1649566435,
					"cart_id": "611a04578537dbc9f1dd54a5",
					"activity_id": "",
					"sku_activity_id": "",
					"conditions_num": "",
					"activity_tag": "",
					"category_path": "",
					"manage_category_path": "193,1026,1029",
					"origin_price": "22.80",
					"size_price": "0.00",
					"add_price": "22.80",
					"add_vip_price": "",
					"price_type": 0,
					"buy_limit": 0,
					"promotion_num": 0,
					"product_name": "冷冻黑虎虾仁 150g",
					"product_type": 0,
					"small_image": "https://ddfs-public.ddimg.mobi/img/blind/product-management/202108/721ce62e15ce4715938af033b2c86dc6.jpg?width=800&height=800",
					"only_new_user": false,
					"is_check": 0,
					"is_gift": 0,
					"is_bulk": 0,
					"view_total_weight": "份",
					"net_weight": "150",
					"net_weight_unit": "g",
					"is_stock": true,
					"old_count": 1,
					"stock_number": 0,
					"not_meet": [],
					"is_presale": 0,
					"presale_id": "",
					"presale_type": 0,
					"delivery_start_time": 0,
					"delivery_end_time": 0,
					"is_invoice": 1,
					"is_onion": 0,
					"sub_list": [],
					"is_booking": 0,
					"today_stockout": "",
					"promotion_info": "",
					"storage_value_id": 3,
					"temperature_layer": "-18℃以下",
					"is_fresh_food": 0
				}]
			}]
		},
		"toast": "",
		"alert": null,
		"all_activity_cart": [],
		"station_id": "5d358b8625e1f7597e8b4569",
		"order_product_list": [],
		"new_order_product_list": [],
		"order_product_list_sign": "d751713988987e9331980363e24189ce",
		"full_to_off": "39.00",
		"freight_money": "5.00",
		"free_freight_type": 99,
		"instant_rebate_money": "0.00",
		"goods_real_money": "0.00",
		"total_money": "0.00",
		"is_select_detail": 1,
		"good_max_count_toast": "订单商品明细行数超过最大限制，无法按商品明细开票",
		"is_all_check": 0,
		"onion_id": "",
		"onion_tip": {},
		"cart_notice": "满39.00元可免配送费",
		"cart_notice_new": "满39.00元可免配送费",
		"free_freight_notice": {},
		"cart_top_floor_info": [],
		"cart_count": 0,
		"total_count": 5,
		"product_num": {
			"609a4060899093cb1f5a6915": 1,
			"5f55fd49f06606002c49a513": 1,
			"60473bca47987eb75d42290f": 1,
			"611a04578537dbc9f1dd54a5": 1,
			"5e8eebcd7cdbf013083016dd": 1
		},
		"stop_order_toast": "",
		"gift_no_size_tip": "",
		"is_hit_onion": false,
		"onion_ab_config": 3,
		"is_hit_gift_size": true,
		"coupon_text_a": "",
		"coupon_text_b": "",
		"need_amount": "",
		"is_vip_ticket": 0,
		"coupon_amount": "",
		"coupon_state": -1,
		"coupon_type": 0,
		"next_recommend_coupon": {
			"coupon_text_a": null,
			"coupon_text_b": null,
			"need_amount": null,
			"is_vip_ticket": null,
			"is_common_ticket": null
		},
		"show_coupon_detail": false,
		"contains_advent_gift": 0,
		"parent_order_info": {
			"parent_order_sign": "d751713988987e9331980363e24189ce",
			"stockout_gift_product": [],
			"stockout_gift_text": "赠品赠完即止，不再补送，敬请谅解。",
			"is_open_presale_use_virtual_stock": false
		},
		"is_support_merge_payment": 1,
		"sodexo_nonsupport_product_list": [],
		"valid_product_counts": {
			"609a4060899093cb1f5a6915": 1,
			"5f55fd49f06606002c49a513": 1
		}
	},
	"tradeTag": "success",
	"server_time": 1649572936,
	"is_trade": 1
}`
成功出单了一次，我从手机把订单取消了，但是再次出单又报错购物车无数据的。

**Comment by dingjingyu** [comment]
我把小程序上的全选都勾上就可以了，谢谢了

**Comment by 1448399491** [comment]
> address

只改了这两个数据好像并不行，换的另一个收货一直提示购物车没东西，我手动勾选完，只要程序运行一次就会自动取消勾选

**Comment by DancingLeaf123** [comment]
> address 和 station id

address 和 station id 都改了不行么？
