### ISSUE TITLE
运行 UserConfig 获取 不了addressId

### ISSUE THREAD

**Issue by will-hu-0** [JannsenYang/dingdong-helper#71]
MacOS的Charles已经在抓包了，可以抓包到IOS上的叮咚微信小程序的信息。
![Jietu20220414-120744](https://user-images.githubusercontent.com/4235291/163312330-1e935003-9add-4f69-a4d8-f882b82373e1.png)
手机小程序未退出，停留在支付画面。

但是一跑UserConfig，就报错
<img width="767" alt="image" src="https://user-images.githubusercontent.com/4235291/163312841-7019c781-3669-4652-b911-25f4be4e1894.png">

Charles抓取 的出错 日志：
![image](https://user-images.githubusercontent.com/4235291/163312349-2212bab8-cec3-4b83-b1f9-fba255be92b4.png)

谢谢

**Comment by JannsenYang** [comment]
看你截图很多参数都没填 ddmc-uid都是空的 看一下我文档中 步骤 第二步 有说明  你把你能看到的和我代码里有的字段都填上去

**Comment by will-hu-0** [comment]
谢谢！
