### ISSUE TITLE
自动勾选购物车全部商品没用，一直提示购物车无可买的商品，需要我去小程序勾选后在运行才能下单，allcheck接口调用我看是成功的，其他人有这情况吗

### ISSUE THREAD

**Issue by mana392** [JannsenYang/dingdong-helper#78]

**Comment by 1448399491** [comment]
那你手动勾选一下啊

**Comment by mana392** [comment]
> 那你手动勾选一下啊


抢的时候卡的页面都进不去，能自己勾的话，手动都能抢到了

**Comment by yedongze** [comment]
> > 那你手动勾选一下啊
> 
> 抢的时候卡的页面都进不去，能自己勾的话，手动都能抢到了

所以为什么不提前加购全选？  一般凌晨就加购全选了。
程序是死的人是活的😄

**Comment by mana392** [comment]
> > > 那你手动勾选一下啊
> > 
> > 
> > 抢的时候卡的页面都进不去，能自己勾的话，手动都能抢到了
> 
> 所以为什么不提前加购全选？ 一般凌晨就加购全选了。 程序是死的人是活的😄

我是用其他地有货的在测试，实际要抢的那地方根本就是无货的，按钮都是灰的呀

**Comment by wJDKnight** [comment]
购物车无可买的商品是正常的，你在叮咚里找找，找几个有货的商品加入购物车试试。

**Comment by mana392** [comment]
> 购物车无可买的商品是正常的，你在叮咚里找找，找几个有货的商品加入购物车试试。

我现在是在测试，用有货的A地址在测，调了自动勾选的，但是还是会返回无货可买，但是其实这个地址是可以买的，因为有货，我在小程序自己勾选了，在跑程序是可以下单的，但是我实际需要去抢的地址是B，那个地址现在没货买不到我知道是正常的，那个地址因为没货所以我也没办法在小程序先勾选

**Comment by JannsenYang** [comment]
> 

我怀疑你的地址或者站点信息配置错误 所以全选按钮够不上 你跑一下UserConfig 确认一下station id和address id  会有提示

**Comment by mana392** [comment]
> > 
> 
> 我怀疑你的地址或者站点信息配置错误 所以全选按钮够不上 你跑一下UserConfig 确认一下station id和address id 会有提示

找到原因了，站点信息是对的，我也以为是站点信息错误，关注点一直也在这上面，最后发现是ddmc-city-number这个错了，因为我测试换了其他地区的，这个会影响查询的new_order_product_list的结果，即使前面调了全选的接口，参数看着有点晕，我的锅，谢谢各位了！
