### ISSUE TITLE
勾选购物车全选按钮失败405。这个也能405的吗？

### ISSUE THREAD

**Issue by wJDKnight** [JannsenYang/dingdong-helper#79]
一直用哨兵模式，上午没问题，下午就405了

**Comment by wJDKnight** [comment]
发现原来是user-agent的问题，不改就可以了。但是更新购物车数据还是405了，(;´༎ຶД༎ຶ`)

**Comment by JannsenYang** [comment]
我也出现了 我知道解决方案了  退出重新登录 app和小程序都退出 小程序重新抓包 更新一下代码 我加了一个运行60次再停10分钟的 看看还会不会出现 没想到这么低频的接口也有风控

**Comment by wJDKnight** [comment]
> 我也出现了 我知道解决方案了 退出重新登录 app和小程序都退出 小程序重新抓包 更新一下代码 我加了一个运行60次再停10分钟的 看看还会不会出现 没想到这么低频的接口也有风控

这样会影响哨兵的效率。我目前是两个号轮流做哨兵。但是哨兵目前还没成功过。在哨兵模式更新出来之前（4月12号）我低频调用，也只成功过两次，一袋青椒，两盒豆腐。感觉还是主要得靠高峰期抢
