### ISSUE TITLE
叮咚在浦东川沙附近的百川站已经贴出了暂停服务公告

### ISSUE THREAD

**Issue by Huzhixin00** [JannsenYang/dingdong-helper#86]
是我家附近这个站点停了，还是其他的站点也都停了呀?

![20220414223514](https://user-images.githubusercontent.com/19983901/163414040-e4cb9833-cec8-4c40-af08-bb7a4c83af42.jpg)

**Comment by JannsenYang** [comment]
单个站点  你可以切换一下收货地址就能看到其他站点信息了

**Comment by imtypist** [comment]
我的app首页也有这个公告，是不是意味着该站点肯定不配送，就没必要刷了？

**Comment by JannsenYang** [comment]
> 我的app首页也有这个公告，是不是意味着该站点肯定不配送，就没必要刷了？

是的

**Comment by Huzhixin00** [comment]
> 单个站点 你可以切换一下收货地址就能看到其他站点信息了

刚早上看了一下，发现很多站点都暂停服务了，目前业主群里得到的消息是，叮咚很多站点要依据政府指令进行仓库的消杀，预计耗时两天，看过两天会不会恢复了。

**Comment by SnoopyGo** [comment]
> 

不知道两三天后恢复是不是真的，感觉很多平价电商平台都被zf关停了，md.
