### ISSUE TITLE
是否考虑开发其它语言的版本

### ISSUE THREAD

**Issue by Louzhichen** [JannsenYang/dingdong-helper#87]
如题

**Comment by JannsenYang** [comment]
如果有时间可以开发nodejs版 python和go不是很拿手 自己写着玩可以 拿出来给大家用可能会出很多问题  但是我个人认为这轮疫情应该不会持续太久了 希望上海能快点让京东正常运营 可以解决很多物资问题 同时也希望这个项目早日结束
