### ISSUE TITLE
为什么提交订单失败呢 是我有参数填写错误了吗？用手机thor抓的包

### ISSUE THREAD

**Issue by 1448399491** [JannsenYang/dingdong-helper#9]

**Comment by binkundai** [comment]
用手机试试呢？我苹果手机上用stream抓包，根据Jannsen的教程step by step很方便就抓到了

**Comment by 1448399491** [comment]
> 用手机试试呢？我苹果手机上用stream抓包，根据Jannsen的教程step by step很方便就抓到了

可以成功运行吗？

**Comment by JannsenYang** [comment]
更新一下代码 之前的版本没有打印错误信息

**Comment by 1448399491** [comment]
> 更新一下代码 之前的版本没有打印错误信息

谢谢 更新了 代码已成功,这个可以用于捡漏吗？

**Comment by 1448399491** [comment]
> 更新一下代码 之前的版本没有打印错误信息

谢谢 更新了 代码已成功,这个可以用于捡漏吗？

**Comment by 1448399491** [comment]
> 更新一下代码 之前的版本没有打印错误信息

谢谢 更新了 代码已成功,这个可以用于捡漏吗？

**Comment by JannsenYang** [comment]
> > 更新一下代码 之前的版本没有打印错误信息
> 
> 谢谢 更新了 代码已成功,这个可以用于捡漏吗？

这个你自己可以去改进  我这个目标是在上海疫情下能吃饱饭 就是每天6点和8点半叮咚会开放购买 此代码的目的是在第一时间下单抢菜  如果不是上海疫情中的体会不到有多难抢

**Comment by 1448399491** [comment]
> > > 更新一下代码 之前的版本没有打印错误信息
> > 
> > 
> > 谢谢 更新了 代码已成功,这个可以用于捡漏吗？
> 
> 这个你自己可以去改进 我这个目标是在上海疫情下能吃饱饭 就是每天6点和8点半叮咚会开放购买 此代码的目的是在第一时间下单抢菜 如果不是上海疫情中的体会不到有多难抢

我就是在上海浦东，很多时候6点和8点半之前不会上架很多东西，有时候白天会补货但是运力已满就下不了单，这个脚本会自动不停的刷新预约时间吗？如果刷出可以预约配送时间会自动下单吗？
