### ISSUE TITLE
最新发现好像没什么用啊？ “删除按钮”还是灰色的

### ISSUE THREAD

**Issue by liaomengge** [JannsenYang/dingdong-helper#97]

**Comment by JannsenYang** [comment]
iphone 11 最新APP版本亲测  来回一直点 有多快就多快 xjb乱按 出不来就没办法了 我的能出来 而且我来回操作了3次

**Comment by liaomengge** [comment]
没用

**Comment by reverse-Man** [comment]
被禁号了，地址修改到别的城市也不能下单了

**Comment by JannsenYang** [comment]
我曾经搞过mt和ele 他们封号是账号自动退出 重新登录的时候提示拨打客服电话解封
叮咚这个看上去完全不像是封账号 因为除了购物车打不开 你可以操作所有的东西 甚至于按我文档中的操作 购物车出现以后还可以下单 所以我判断这不是风控而且最近失效的商品太多了 叮咚服务器出现了偶发Bug  如果实在没法解决可以试着拨打客服电话咨询

**Comment by cuipengcx** [comment]
> 

作者  我现在获取配送时间接口，一直提示"当前人多拥挤，请刷新重试"（手机app正常下单选择时间也是这样），其他访问正常，只有获取配送时间，是不是风控了？

**Comment by JannsenYang** [comment]
> > 
> 
> 作者 我现在获取配送时间接口，一直提示"当前人多拥挤，请刷新重试"（手机app正常下单选择时间也是这样），其他访问正常，只有获取配送时间，是不是风控了？

重新登录一下试试

**Comment by happytogether** [comment]
我也是获取配送时间接口，一直提示"当前人多拥挤，请刷新重试"（手机app正常下单选择时间也是这样），其他访问正常。重新登陆还是一样的。这样是风控嘛？

**Comment by cuipengcx** [comment]
> > > 
> > 
> > 
> > 作者 我现在获取配送时间接口，一直提示"当前人多拥挤，请刷新重试"（手机app正常下单选择时间也是这样），其他访问正常，只有获取配送时间，是不是风控了？
> 
> 重新登录一下试试

重新登录 还是不行，看来是被风控了
